# 分发证书
- name: 获取 etcd 相关证书
  slurp:
    src: /etc/kubernetes/pki/etcd/{{ item }} 
  with_items:
  - ca.crt
  - ca.key
  - healthcheck-client.crt
  - healthcheck-client.key
  - peer.crt
  - peer.key
  - server.crt
  - server.key
  register: etcd_certs
  delegate_to: "{{ groups['etcd'][0] }}"
  run_once: true

- name: 分发 etcd 相关证书到 etcd 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ etcd_certs.results }}"
  when: 
  - inventory_hostname != groups['etcd'][0] 
  - inventory_hostname in (groups['etcd'] + groups['new-etcd'])

- name: 获取 apiserver etcd client 证书
  slurp:
    src: /etc/kubernetes/pki/{{ item }} 
  with_items:
  - etcd/ca.crt
  - apiserver-etcd-client.crt
  - apiserver-etcd-client.key
  register: etcd_client_certs
  delegate_to: "{{ groups['etcd'][0] }}"
  run_once: true

- name: 分发 apiserver etcd client 证书到 master 节点
  copy:
    dest: "{{ item.source }}"
    content: "{{ item.content | b64decode }}"
    owner: root
    group: root
    mode: 0644
  no_log: true
  with_items: "{{ etcd_client_certs.results }}"
  when: 
  - inventory_hostname != groups['etcd'][0] 
  - inventory_hostname in (groups['kube-master'] + groups['new-master'])