- name: 生成 Docker GPG 公钥
  copy:
    src: docker.gpg
    dest: /tmp/docker.gpg
    owner: root
    mode: 0644

- name: 添加 Docker GPG 公钥
  shell: apt-key add /tmp/docker.gpg

- name: 添加 Docker apt 仓库
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: 安装 containerd
  apt: 
    name:
    - "containerd.io={{ containerd_version }}"
    state: present
    allow_unauthenticated: true